#!/bin/sh

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Init submodules"
yadm submodule update --recursive --init

# Install basic packages
sudo apt update -y
sudo apt upgrade -y
sudo apt install -y vim python ansible emacs neovim

# Install SpaceVim
[[ -d $HOME/.SpaceVim ]] || bash $HOME/bin/spacevim_install.sh

