#!/bin/sh

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"
# yadm commands here

# Create some needed dirs
mkdir -p $HOME/.ssh/config.d
touch $HOME/.ssh/config.d/hosts

mkdir -p $HOME/.tmux/plugins


# Clone base repos

mkdir -p $HOME/repos
cd $HOME/repos

if [ ! -d $HOME/repos/tpm ]; then
git clone --depth 1 https://github.com/tmux-plugins/tpm.git
ln -s $HOME/repos/tpm $HOME/.tmux/plugins/tpm
fi

if [ ! -d $HOME/repos/SpaceVim ]; then
git clone --depth 1 https://github.com/SpaceVim/SpaceVim.git
bash $HOME/repos/SpaceVim/docs/install.sh
fi

if [ ! -d $HOME/repos/fonts ]; then
git clone --depth 1 https://github.com/powerline/fonts.git
bash $HOME/repos/fonts/install.sh
fi

if [ ! -d $HOME/repos/doom-emacs ]; then
git clone --depth 1 https://github.com/hlissner/doom-emacs.git
ln -s $HOME/repos/doom-emacs $HOME/.emacs.d
~/.emacs.d/bin/doom install
fi

# This is for wayland
ln -s $HOME/.Xresources $HOME/.Xdefaults

