# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 6000

  config.vm.box = "ubuntu/eoan64"

  config.vm.hostname = "devenv"

  config.vm.network "public_network"

  config.vm.synced_folder ENV['HOME'], "/home/vagrant", automount: true

  config.vbguest.auto_update = true

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true

    #  https://bugs.launchpad.net/cloud-images/+bug/1829625
    vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
    vb.customize ["modifyvm", :id, "--uartmode1", "file", "./ttyS0.log"]

    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

    vb.name = "devenv"
    vb.memory = "2048"
    vb.cpus = 4
  end

  config.vm.provision "basic", type: "ansible_local", run: "always" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
