- hosts: localhost
  become: true
  tasks:
  - name: Install snaps
    command: snap install {{item}}
    with_items:
      - firefox
      - vlc
      - gimp
      - libreoffice
      - telegram-desktop
      - spotify
      - cool-retro-term
  - name: Install classic snaps
    command: snap install {{item}} --classic
    with_items:
      - skype
      - vscode

