- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    package: name={{item}}
    with_items:
      - git-core 
      - gitk 
      - git-gui 
      - subversion 
      - curl 
      - lvm2 
      - thin-provisioning-tools 
      - python-pkg-resources 
      - python-virtualenv 
      - python-oauth2client
  - name: Clone depot-tools
    become: no
    git:
      repo: https://chromium.googlesource.com/chromium/tools/depot_tools.git
      dest: "{{ lookup('env', 'HOME') }}/Repos/depot_tools"
  #- name: Verifica ambiente
  #  become: no
  #  assert: { that: "'{{ lookup('env', 'HOME') }}/Repos/depot_tools' is search('{{ lookup('env', 'PATH') }}'')" }

  # echo '=== FIX UP SUDO ==='
##http://www.chromium.org/tips-and-tricks-for-chromium-os-developers#TOC-Making-sudo-a-little-more-permissive
#cat<<SUDO1 | sudo tee /etc/sudoers.d/relax_requirements
#Defaults !tty_tickets # Entering your password in one shell affects all shells
#Defaults timestamp_timeout=180 # Minutes between re-requesting your password
#SUDO1
#sudo chmod 0440 /etc/sudoers.d/relax_requirements

