- hosts: localhost
  become: true
  tasks:
  - name: Install cli tools
    package: name={{item}}
    with_items:
      - alacritty
      - htop
      - yadm
      - curl
      - wget
      - vim
      - vim-scripts
      - xclip
      - patch
      - less
      - git-email
      - docker
      - docker-compose
      - build-essential 
      - git-flow
      - tmux
      - neovim
      - bat
      - byobu
      - cmatrix
      - clamav
      - colordiff
      - elinks
      - google-drive-ocamlfuse
      - inotify-tools
      - lynis
      - pandoc
      - ncdu
      - pass
      - tcpdump
      - tldr
      - virtualbox-guest-utils
      - yay
      - iftop
      - iotop
      - iptraf-ng
      - github-cli
  - name: Install dev tools
    package: name={{item}}
    with_items:
      - bison
      - clang
      - flex
      - julia
      - kotlin
      - gcc
      - make
      - automake
      - perl
      - python
      - emacs
      - go-tools
      - maven
  - name: Install desktop apps
    package: name={{item}}
    with_items:
      - calibre
      - code
      - lyx
      - evince
      - firefox
      - gimp
      - google-chrome
      - gparted
      - intellij-idea-community-edition
      - pidgin
      - postman
      - remmina
      - sigil
      - slack-desktop
      - vlc
      - zoom
  - name: Create a directory if it does not exist
    file:
      path: $HOME/repos
      state: directory
      mode: '0755'
  - name: Clone / update doom emacs
    become: false
    git:
      become: false
      repo: git@github.com:hlissner/doom-emacs.git 
      dest: $HOME/repos
      clone: yes
      update: yes
      depth: 1
      bare: yes
  - name: Create a symbolic link to doom
    become: false
    file:
      src: $HOME/.emacs.d
      dest: $HOME/repos/doom-emacs
      state: link
  - name: Install doom
    become: false
    command: ./doom install
    args:
      chdir: $HOME/.emacs.d/bin
      creates: $HOME/.doom.d
  - name: Clone dotfiles
    become: false
    command: yadm clone git@github.com:suderio/dotfiles.git
    args:
      chdir: $HOME
      creates: $HOME/.config/yadm
  - name: Clone SpaceVim
    become: false
    git:
      become: false
      repo: git@github.com:SpaceVim/SpaceVim.git
      dest: $HOME/repos
      clone: yes
      update: yes
      depth: 1
      bare: yes
  - name: Install SpaceVim
    become: false
    command: install.sh
    args:
      chdir: $HOME/repos/Spacevim/docs
      creates: $HOME/.SpaceVim


#aic94xx-firmware
#aspell-en
#aspell-pt
#dhcpcd
#fd
#file-roller
#ktlint-git
#mps-youtube-git
#nbd
#pkgconf
#pkgfile
#powerline
#python-pipx
#python-poetry
#rundeck-cli
#rxvt-unicode
#shellcheck
#sysstat
#transset-df
#twinejs-standalone
#vim-ansible
#wd719x-firmware
#wtfutil-bin
#zerofree

#libreoffice
#telegram-desktop
#spotify
#cool-retro-term
#skype

#adwaita-qt
#alsa-utils
#ansible-lint
#arch-audit
#archiso
#aurphan
#autojump-git
#base
#chrome-gnome-shell
#chromium
#chromium-widevine
#dconf-editor
#fontforge
#gdm
#gnome-backgrounds
#gnome-shell-extensions
#gnome-tweaks
#grub-customizer
#man-pages
#nethogs
#notmuch
#ntop
#openoffice
#pacman-contrib
#xdg-user-dirs
#xf86-video-dummy
#xf86-video-fbdev
#xf86-video-vesa
#xorg-docs
#xorg-fonts-100dpi
#xorg-fonts-75dpi
#xorg-iceauth
#xorg-server-devel
#xorg-server-xnest
#xorg-server-xvfb
#xorg-sessreg
#xorg-smproxy
#xorg-x11perf
#xorg-xbacklight
#xorg-xclock
#xorg-xcmsdb
#xorg-xcursorgen
#xorg-xdpyinfo
#xorg-xdriinfo
#xorg-xev
#xorg-xgamma
#xorg-xinit
#xorg-xinput
#xorg-xkbevd
#xorg-xkbutils
#xorg-xkill
#xorg-xlsatoms
#xorg-xlsclients
#xorg-xpr
#xorg-xrefresh
#xorg-xsetroot
#xorg-xvinfo
#xorg-xwd
#xorg-xwininfo
#xorg-xwud
#yadm-git
