- hosts: localhost
  become: true
  tasks:
  - name: Distribution
    debug: msg={{ ansible_distribution }}
  - name: Install cli tools
    package: name={{item}}
    with_items:
      - alacritty
      - htop
      - curl
      - wget
      - vim
      - xclip
      - patch
      - less
      - docker
      - docker-compose
      - tmux
      - neovim
      - bat
      - byobu
      - cmatrix
      - clamav
      - colordiff
      - elinks
      - inotify-tools
      - lynis
      - pandoc
      - ncdu
      - pass
      - tcpdump
      - tldr
      - virtualbox-guest-utils
      - iftop
      - iotop
      - iptraf-ng
      - github-cli
      - powerline-fonts
  - name: Install arch cli tools
    package: name={{item}}
    with_items:
      - base-devel # yay needs this
      - yay
      - plank # only in xfce? this is for mac os theme
    when: ansible_distribution == "Archlinux"
  - name: Install dev tools
    package: name={{item}}
    with_items:
      - bison
      - clang
      - flex
      - julia
      - kotlin
      - gcc
      - make
      - automake
      - perl
      - python
      - emacs
      - go-tools
      - maven
  - name: Install desktop apps
    package: name={{item}}
    with_items:
      - calibre
      - code
      - lyx
      - evince
      - firefox
      - gimp
      - gparted
      - intellij-idea-community-edition
      - pidgin
      - remmina
      - sigil
      - vlc
  - name: Doom emacs dependencies
    package: name={{item}}
    with_items:
      - ripgrep
      - fd
  - name: Install aur programs
    become: false
    command: yay -S --answerclean None --answeredit None --answerdiff None --quiet --noconfirm {{item}}
    with_items:
      - aur/yadm
      - google-drive-ocamlfuse
      - google-chrome
      - postman-bin
      - slack-desktop
      - zoom
      - discord
      - oh-my-bash-git
      - oh-my-zsh-git
  - name: Install aur doom emacs dependencies
    become: false
    command: yay -S --answerclean None --answeredit None --answerdiff None --quiet --noconfirm {{item}}
    with_items:
      - ttf-all-the-icons
